PREFIX  cao:  <http://my.campus.org/communicative-acts#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ieso: <https://www.gecad.isep.ipp.pt/ieso/v1.1.0/>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  time: <http://www.w3.org/2006/time#>

CONSTRUCT 
  { 
    _:c0 rdf:type cao:CurrentGenerationInform .
    _:c0 cao:currentGeneration _:c1 .
    _:c1 rdf:type ieso:Energy .
    _:c1 ieso:hasDateTime "<[MEASUREMENT_DATETIME]>"^^xsd:dateTime .
    _:c1 ieso:hasMeasurementValue _:c2 .
    _:c2 rdf:type ieso:MeasurementValue .
    _:c2 ieso:hasUnitOfMeasure ieso:Kilowatt .
    _:c2 ieso:hasLiteralValue "<[GENERATION]>"^^rdfs:Literal .
    _:c0 time:hasBeginning _:c3 .
    _:c3 rdf:type time:Instant .
    _:c3 time:inXSDDateTimeStamp "<[BEGINNING]>"^^xsd:DateTimeStamp .
    _:c0 time:hasEnd _:c4 .
    _:c4 rdf:type time:Instant .
    _:c4 time:inXSDDateTimeStamp "<[END]>"^^xsd:DateTimeStamp .
    _:c0 time:hasTime _:c5 .
    _:c5 rdf:type time:Instant .
    _:c5 time:inXSDDateTimeStamp ?dt .
  }
WHERE
  { BIND(now() AS ?dt) }