PREFIX  cao:  <http://my.campus.org/communicative-acts#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  time: <http://www.w3.org/2006/time#>

SELECT  ?dict
WHERE
  { _:b0  rdf:type              cao:ConsumptionForecastRequest ;
          time:hasBeggining     _:b1 .
    _:b1  rdf:type              time:Instant ;
          time:inXSDDateTimeStamp  ?start .
    _:b0  time:hasEnd           _:b2 .
    _:b2  rdf:type              time:Instant ;
          time:inXSDDateTimeStamp  ?end .
    _:b0  time:hasTime          _:b3 .
    _:b3  rdf:type              time:Instant ;
          time:inXSDDateTimeStamp  ?dt
    BIND(concat("{\"message_type\":\"ConsumptionForecastRequest\",\"has_beggining\":\"", str(?start), "\",\"has_end\":\"", str(?end), "\",\"timestamp\":\"", str(?dt), "\"}") AS ?dict)
  }