PREFIX  cao:  <http://my.campus.org/communicative-acts#>
PREFIX  time: <http://www.w3.org/2006/time#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT 
  { 
    _:c0 rdf:type cao:DeviceControlRequest .
    _:c0 cao:controlDevice <[DEVICE_IRI]> .
    _:c0 cao:controlAction <[ACTUATION_ACTION_IRI]> .
    _:c0 time:hasTime _:c2 .
    _:c2 rdf:type time:Instant .
    _:c2 time:inXSDDateTimeStamp ?dt .
  }
WHERE
  { BIND(now() AS ?dt) }